  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'June', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['fernanda@nnido.com.ar', 'lester@hellolucy.io', 'shelby@hellolucy.io', 'joshua@hellolucy.io', 'allie@hellolucy.io', 'john@hellolucy.io', 'diego.mdq.91@hotmail.com', 'jiayi@hellolucy.io’, samantha@hellolucy.io] # You can list more emails here
    groups = values[:test_email] ? nil : ['Internal'] # You can define groups on the web and reference them here

    crashlytics(api_token: '40bf0b38845aa3797d152590d2f88b7bd0883593',
             build_secret: 'd3a541e0bcb49f23e57b2c4d8b7748c0a722a1a680a61defb03eb38c5a865bff',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end