# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamsTemplate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DreamsTemplate

#pod 'CodableAlamofire'
  pod 'Alamofire', '~> 4.7'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~>3.7'
  pod 'MarqueeLabel/Swift'
  pod 'JGProgressHUD'
  pod 'JKNotificationPanel'
  pod 'Charts'
  pod 'FSLineChart'

  target 'DreamsTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DreamsTemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
